#jeka.version=0.11.59
#jeka.classpath=../javafx-plugin/.jeka-work/jeka-src-classes
jeka.classpath=dev.jeka:javafx-plugin:0.11.59-0

@project.javaVersion=23
@project.pack.mainClass=com.github.reugn.devtools.Main
@project.pack.jarType=FAT

@javafx=on

@bundle.includeRuntimeLibs=true
@bundle.jpackage.options.all.--name=jfx-dev-tools
@bundle.jpackage.options.mac.--icon=icons/icon.icns
@bundle.jpackage.options.windows.--icon=icons/icon.png


